pool:
  name: Azure Pipelines
trigger:
  branches:
    include:
      - main
steps:
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: dockerhub
    repository: 'bjgomes/movie_apps'
    Dockerfile: dockerfile